arr = [5,8,9,10,12]
console.log(arr.includes(9));  //IT RETURNS BOOLEAN DATATYPE 

console.log(arr.indexOf(10)); // IT RETURNS THE INDEX OF THE ELEMENT ...
console.log(arr.indexOf(15)); // IF THE ELEMENT IS NOT PRESENT IT RETURNS -1 ...

console.log(arr.reverse()); // IT REVERSES THE ARRAY ...

// for joining of two array 
let arr2 = [1,2,3,4]
    a3 = arr.join(arr2);
    console.log(a3);  // it will join the two array with comma in between ...