// At method in array is used find the index value...
let a1=[1,2,3,4,5]
console.log(a1.at(2)); // it will return the element at index 2 ...


let a2=[6,7,8,9]
console.log(a1.concat(a2)); // it will join the two array without comma in between ...

a1 = a1.concat(a2);
console.log(a1); //it will join the two array without comma in between ...


//! Slicing of array ...
let arr = [1,2,3,4,5,6,7,8,9]
console.log(arr.slice(2)); // it will slice the array from index 2 to end ...
console.log(arr.slice(2,5)); // it will slice the array from index 2 to index 5 but not including index 5 ...